FIND_PATH(ID3tag_INCLUDE_DIRS ID3tag.h)

FIND_LIBRARY(ID3tag_LIBRARIES NAMES ID3tag)

IF (ID3tag_INCLUDE_DIRS AND ID3tag_LIBRARIES)
   SET(ID3tag_FOUND TRUE)
ENDIF (ID3tag_INCLUDE_DIRS AND ID3tag_LIBRARIES)


IF (ID3tag_FOUND)
   IF (NOT ID3tag_FIND_QUIETLY)
      MESSAGE(STATUS "Found libID3tag: ${ID3tag_LIBRARIES}")
   ENDIF (NOT ID3tag_FIND_QUIETLY)
ELSE (ID3tag_FOUND)
   IF (ID3tag_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find libID3tag")
   ENDIF (ID3tag_FIND_REQUIRED)
ENDIF (ID3tag_FOUND)